// backend/src/auth/oidc.errors.mjs
export const OIDC_ERRORS = {
  TENANT_NOT_RESOLVED: "OIDC_TENANT_NOT_RESOLVED",
  CONFIG_INCOMPLETE: "OIDC_CONFIG_INCOMPLETE",
  INVALID_CALLBACK: "OIDC_INVALID_CALLBACK",
  TOKEN_EXCHANGE_FAILED: "OIDC_TOKEN_EXCHANGE_FAILED",
};
