// Stable error codes for B3 (ledger writes only). Do not rename once shipped.

export const LedgerErrorCodes = Object.freeze({
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",

  TENANT_UNRESOLVED: "TENANT_UNRESOLVED",
  TENANT_FORBIDDEN: "TENANT_FORBIDDEN",

  LEDGER_VALIDATION_FAILED: "LEDGER_VALIDATION_FAILED",
  LEDGER_EVENTTYPE_INVALID: "LEDGER_EVENTTYPE_INVALID",
  LEDGER_QUANTITY_INVALID: "LEDGER_QUANTITY_INVALID",
  LEDGER_MOVE_INVALID: "LEDGER_MOVE_INVALID",

  IDEMPOTENT_REPLAY: "IDEMPOTENT_REPLAY",
  IDEMPOTENCY_KEY_REUSE_MISMATCH: "IDEMPOTENCY_KEY_REUSE_MISMATCH",

  LEDGER_STORE_APPEND_FAILED: "LEDGER_STORE_APPEND_FAILED",
  LEDGER_CONFLICT: "LEDGER_CONFLICT",
});
